# NumPy Broadcasting and Vectorized Operations

Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations to be performed on arrays of **different shapes**. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes.

This tutorial covers:
1. **What is Broadcasting?**
2. **Broadcasting Rules and Compatibility**
3. **Practical Examples** (Scalar-to-Array, 1D-to-2D, and Row-to-Column)
4. **Non-compatible Shapes** (Understanding `ValueError`)

In [1]:
import numpy as np

## 1. Scalar-to-Array Broadcasting

The simplest example of broadcasting is multiplying or adding a scalar to an array. NumPy automatically stretches the scalar value to match the shape of the array.

In [2]:
arr = np.array([1, 2, 3])
print("Original Array:\n", arr)

# The scalar 5 is treated as an array of shape (1,) and broadcast to shape (3,)
result = arr + 5
print("After Adding Scalar 5:\n", result)

Original Array:
 [1 2 3]
After Adding Scalar 5:
 [6 7 8]


## 2. General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the **trailing (rightmost) dimensions** and works its way left. Two dimensions are compatible if:
1. **They are equal**, or
2. **One of them is 1**.

If these conditions are not met, a `ValueError: operands could not be broadcast together` is thrown.

## 3. Practical Examples

### Example A: Adding a 1D Array to a 2D Array
Let's add a 1D array of shape `(3,)` to a 2D array of shape `(2, 3)`.
- Array A shape: `(2, 3)`
- Array B shape: `   (3,)` (NumPy prepends a 1 to make it `(1, 3)`)
- Trailing dimensions are both `3` (equal) and leading dimensions are `2` and `1` (one is 1). Broadcasting succeeds!

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

print("2D Array (A):\n", A)
print("1D Array (B):\n", B)

# Adding 1D array B to each row of 2D array A
result_ab = A + B
print("Result (A + B):\n", result_ab)

2D Array (A):
 [[ 1  2  3]
 [ 4  5  6]]
1D Array (B):
 [10 20 30]
Result (A + B):
 [[11 22 33]
 [14 25 36]]


### Example B: Row Vector and Column Vector
Let's combine a column vector of shape `(3, 1)` and a row vector of shape `(1, 3)`.
- Column Vector shape: `(3, 1)`
- Row Vector shape:    `(1, 3)`
- NumPy stretches both dimensions: `(3, 1)` becomes `(3, 3)` and `(1, 3)` becomes `(3, 3)`. The resulting shape will be `(3, 3)`.

In [4]:
col = np.array([[1], [2], [3]])  # Shape (3, 1)
row = np.array([10, 20, 30])      # Shape (3,)

print("Column Vector (Col):\n", col)
print("Row Vector (Row):\n", row)

result_cr = col + row
print("Result Matrix (Col + Row):\n", result_cr)

Column Vector (Col):
 [[1]
 [2]
 [3]]
Row Vector (Row):
 [10 20 30]
Result Matrix (Col + Row):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 4. Non-compatible Shapes (Understanding Broadcasting Errors)

Let's look at an example where broadcasting fails. Suppose we attempt to add a 1D array of shape `(2,)` to a 2D array of shape `(2, 3)`.
- Array A shape: `(2, 3)`
- Array B shape: `   (2,)` (NumPy prepends a 1 to make it `(1, 2)`)
- Comparing trailing dimensions: `3` and `2` do not match, and neither is `1`.

Let's verify this using Python exception handling.

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
B = np.array([10, 20])                 # Shape (2,)

try:
    result = A + B
except ValueError as e:
    print("Error successfully caught:", e)

Error successfully caught: operands could not be broadcast together with shapes (2,3) (2,)
