In [1]:
import numpy as np


# Useful Mathematical and Statistical Functions in NumPy

NumPy provides an extensive collection of mathematical, statistical, and algebraic functions that operate efficiently over entire arrays without requiring explicit Python loops.

Let's explore these functions categorized by their utility.

## 1. Basic Reductions: Sum and Product

These functions aggregate array elements into a single scalar value or along a specified axis.

* **`np.sum()`**: Calculates the sum of array elements.
* **`np.prod()`**: Calculates the product of array elements.

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Array:\n", arr)

# 1. Sum
print("\n--- Sum ---")
print("Total sum:", np.sum(arr))
print("Sum along columns (axis=0):", np.sum(arr, axis=0))
print("Sum along rows (axis=1):", np.sum(arr, axis=1))

# 2. Product
print("\n--- Product ---")
print("Total product:", np.prod(arr))
print("Product along columns (axis=0):", np.prod(arr, axis=0))
print("Product along rows (axis=1):", np.prod(arr, axis=1))

Original 2D Array:
 [[1 2 3]
 [4 5 6]]

--- Sum ---
Total sum: 21
Sum along columns (axis=0): [5 7 9]
Sum along rows (axis=1): [ 6 15]

--- Product ---
Total product: 720
Product along columns (axis=0): [ 4 10 18]
Product along rows (axis=1): [  6 120]


## 2. Minimum, Maximum, and Indices (Argmin, Argmax)

These functions are used to find extreme values and their locations in an array.

* **`np.min()` / `np.max()`**: Find the minimum and maximum values.
* **`np.argmin()` / `np.argmax()`**: Find the *indices* of the minimum and maximum values.

In [3]:
data = np.array([12, 45, 2, 89, 34, 7])
print("Array:", data)

# Min & Max
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))

# Argmin & Argmax (Indices of min/max)
min_idx = np.argmin(data)
max_idx = np.argmax(data)
print("Index of minimum value:", min_idx, f"(Value is {data[min_idx]})")
print("Index of maximum value:", max_idx, f"(Value is {data[max_idx]})")

# 2D Example
matrix = np.array([[10, 20, 5], [15, 3, 25]])
print("\n2D Matrix:\n", matrix)
print("Argmax along columns (axis=0):", np.argmax(matrix, axis=0))
print("Argmax along rows (axis=1):", np.argmax(matrix, axis=1))

Array: [12 45  2 89 34  7]
Minimum value: 2
Maximum value: 89
Index of minimum value: 2 (Value is 2)
Index of maximum value: 3 (Value is 89)

2D Matrix:
 [[10 20  5]
 [15  3 25]]
Argmax along columns (axis=0): [1 0 1]
Argmax along rows (axis=1): [1 2]


## 3. Statistical Functions: Mean, Median, Standard Deviation, and Variance

NumPy provides standard statistical metrics to describe the central tendency and dispersion of data.

* **`np.mean()`**: Compute the arithmetic mean (average).
* **`np.median()`**: Compute the median (middle value).
* **`np.std()`**: Compute the standard deviation (measure of spread).
* **`np.var()`**: Compute the variance (square of standard deviation).

In [4]:
scores = np.array([85, 90, 78, 92, 88, 95, 40]) # Note the outlier value of 40
print("Scores:", scores)

print("Mean score:   ", np.mean(scores))
print("Median score: ", np.median(scores))
print("Variance:     ", np.var(scores))
print("Std Deviation:", np.std(scores))

# Axis-based stats in 2D array
matrix_stats = np.array([[1, 2], [3, 10]])
print("\nMatrix:\n", matrix_stats)
print("Mean along columns (axis=0):", np.mean(matrix_stats, axis=0))

Scores: [85 90 78 92 88 95 40]
Mean score:    81.14285714285714
Median score:  88.0
Variance:      307.55102040816325
Std Deviation: 17.537132616484463

Matrix:
 [[ 1  2]
 [ 3 10]]
Mean along columns (axis=0): [2. 6.]


## 4. Power and Root Functions

Functions to perform exponentiation and root calculations.

* **`np.power()`**: Raise elements to a power.
* **`np.square()`**: Square each element ($x^2$).
* **`np.sqrt()`**: Compute the non-negative square root ($\sqrt{x}$).

In [5]:
x = np.array([1, 4, 9, 16])
print("Original array x:", x)

# Exponentiation
print("Square of x (np.square):   ", np.square(x))
print("Cube of x (np.power(x, 3)):", np.power(x, 3))

# Roots
print("Square root of x (np.sqrt):", np.sqrt(x))

Original array x: [ 1  4  9 16]
Square of x (np.square):    [  1  16  81 256]
Cube of x (np.power(x, 3)): [   1   64  729 4096]
Square root of x (np.sqrt): [1. 2. 3. 4.]


## 5. Exponentials and Logarithmic Functions

Logarithmic and exponential functions are crucial in calculus, probability, and scaling distributions.

* **`np.exp()`**: Compute the exponential ($e^x$).
* **`np.log()`**: Natural logarithm (base $e$).
* **`np.log10()`**: Base-10 logarithm.
* **`np.log2()`**: Base-2 logarithm.

In [6]:
vals = np.array([1, 2, 10, 100])
print("Values:", vals)

# Exponentials
print("e^x (np.exp):", np.exp(np.array([0, 1, 2])))

# Logarithms
print("Natural log (np.log):  ", np.log(vals))
print("Base-10 log (np.log10):", np.log10(vals))
print("Base-2 log (np.log2):  ", np.log2(np.array([1, 2, 4, 8])))

Values: [  1   2  10 100]
e^x (np.exp): [1.         2.71828183 7.3890561 ]
Natural log (np.log):   [0.         0.69314718 2.30258509 4.60517019]
Base-10 log (np.log10): [0.      0.30103 1.      2.     ]
Base-2 log (np.log2):   [0. 1. 2. 3.]


## 6. Rounding Functions

Functions to convert floats to nearby integer values or round to decimals.

* **`np.round()`**: Round to the nearest integer or specified decimals.
* **`np.floor()`**: Round down (towards negative infinity).
* **`np.ceil()`**: Round up (towards positive infinity).
* **`np.trunc()`**: Truncate (discard decimal part, round towards zero).

In [7]:
floats = np.array([-1.7, -1.2, 0.2, 1.5, 1.8, 2.3])
print("Floats:", floats)

print("np.round(floats):", np.round(floats))
print("np.floor(floats):", np.floor(floats))
print("np.ceil(floats): ", np.ceil(floats))
print("np.trunc(floats):", np.trunc(floats))

# Rounding to specific decimals
pi_vals = np.array([3.14159, 2.71828])
print("\nRounding to 2 decimal places:", np.round(pi_vals, 2))

Floats: [-1.7 -1.2  0.2  1.5  1.8  2.3]
np.round(floats): [-2. -1.  0.  2.  2.  2.]
np.floor(floats): [-2. -2.  0.  1.  1.  2.]
np.ceil(floats):  [-1. -1.  1.  2.  2.  3.]
np.trunc(floats): [-1. -1.  0.  1.  1.  2.]

Rounding to 2 decimal places: [3.14 2.72]


## 7. Miscellaneous Functions

Highly useful utility functions for day-to-day data manipulation.

* **`np.abs()`** / **`np.absolute()`**: Compute the absolute (positive) values.
* **`np.clip()`**: Limit the values in an array to a specified interval (min, max threshold).
* **`np.unique()`**: Find the unique elements of an array.
* **`np.sign()`**: Returns `-1` for negative numbers, `0` for zero, and `1` for positive numbers.

In [8]:
mixed = np.array([-10, -5, 0, 5, 20])
print("Mixed array:", mixed)

# Absolute and Sign
print("Absolute values (np.abs):", np.abs(mixed))
print("Signs (np.sign):         ", np.sign(mixed))

# Clip (e.g., clamp between -3 and 10)
# Values less than -3 become -3, and values greater than 10 become 10.
print("Clipped (min=-3, max=10):", np.clip(mixed, -3, 10))

# Unique
duplicates = np.array([1, 2, 2, 3, 1, 4, 2, 5, 5])
print("\nArray with duplicates:", duplicates)
print("Unique elements (np.unique):", np.unique(duplicates))

Mixed array: [-10  -5   0   5  20]
Absolute values (np.abs): [10  5  0  5 20]
Signs (np.sign):          [-1 -1  0  1  1]
Clipped (min=-3, max=10): [-3 -3  0  5 10]

Array with duplicates: [1 2 2 3 1 4 2 5 5]
Unique elements (np.unique): [1 2 3 4 5]
