In [4]:

# Useful Attributes
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr.shape) # Dimensions - (4 x 3)
print(arr.size) # Total elements - (12)
print(arr.ndim) # Number of dimensions - 2
print(arr.dtype) # Data type object - int64
print(arr.itemsize) # Size of each element in bytes - 8 for int64

# Specify dtype at creation
str_arr = np.array([1, 2, 3], dtype="U")
print(str_arr, str_arr.dtype)
float_arr = np.array([1, 2, 3], dtype="float64")
print(float_arr, float_arr.dtype)
# Creating new array with a specific type from existing array
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)


(4, 3)
12
2
int64
8
['1' '2' '3'] <U1
[1. 2. 3.] float64
[1 2 3] int64


In [5]:
# Creating NumPy Arrays - from scratch
arr1 = np.zeros((3, 4)) # 3x4 array of 0s
print(arr1, arr1.shape)
arr2 = np.ones((3, 3)) # 3x3 array of 1s
print(arr2, arr2.shape)
arr3 = np.full((2, 3), 5) # 2x3 array of 5s
print(arr3, arr3.shape)
arr4 = np.eye(3) # Identity matrix of 3x3
print(arr4, arr4.shape)
arr5 = np.arange(1, 20, 2) # Elements in range(1, 20)
print(arr5, arr5.shape)
arr6 = np.linspace(0, 10, 5) # 5 elements linearly spaced from 0 to 10
print(arr6, arr6.shape)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)


In [ ]:
# Useful Attributes
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr.shape) # Dimensions - (4 x 3)
print(arr.size) # Total elements - (12)
print(arr.ndim) # Number of dimensions - 2
print(arr.dtype) # Data type object - int64
print(arr.itemsize) # Size of each element in bytes - 8 for int64

# Specify dtype at creation
str_arr = np.array([1, 2, 3], dtype="U")
print(str_arr, str_arr.dtype)
float_arr = np.array([1, 2, 3], dtype="float64")
print(float_arr, float_arr.dtype)

# Creating new array with a specific type from existing array
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)
